const baseTheme = {
    baseText: 'text-slate-900',
    mutedText: 'text-slate-600',
    mutedTextLight: 'text-slate-400',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardText: 'text-slate-900',
    subHeaderText: 'text-slate-700',
    labelText: 'text-slate-700',
    noteText: 'text-slate-600',
    noteBorder: 'border-slate-100',
    timestampText: 'text-slate-500',
    divider: 'border-slate-100',
    inputBg: 'bg-white',
    inputBorder: 'border-slate-300',
    inputFocus: 'focus:ring-slate-500 focus:border-slate-500',
    selectFocus: 'focus:ring-slate-500 focus:border-slate-500',
    buttonBg: 'bg-slate-900',
    buttonHover: 'hover:bg-slate-800',
    buttonText: 'text-white',
    neutralButtonBg: 'bg-white',
    neutralButtonBorder: 'border-slate-200',
    neutralButtonText: 'text-slate-700',
    neutralButtonHover: 'hover:bg-slate-50',
    infoButtonBg: 'bg-slate-50',
    infoButtonBorder: 'border-slate-200',
    infoButtonText: 'text-slate-600',
    infoButtonHover: 'hover:bg-slate-100',
    accentSoftBg: 'bg-slate-50',
    accentSoftBorder: 'border-slate-200',
    accentSoftText: 'text-slate-700',
    accentSoftHover: 'hover:bg-slate-100',
    statusAttentionBg: 'bg-rose-100',
    statusAttentionText: 'text-rose-700',
    statusGoodBg: 'bg-emerald-100',
    statusGoodText: 'text-emerald-700',
    statusNeutralBg: 'bg-slate-100',
    statusNeutralText: 'text-slate-700',
    iconFood: 'text-slate-500',
    iconWheel: 'text-slate-500',
    iconActivity: 'text-slate-500',
    chartStrokeWheel: '#0f172a',
    chartStrokeFood: '#334155',
    aiCardBgBase: 'bg-white/80',
    aiCardBgFrom: 'from-slate-50',
    aiCardBgTo: 'to-slate-50',
    aiCardBorder: 'border-slate-100',
    aiHeading: 'text-slate-900',
    aiAccentText: 'text-slate-600',
    aiButtonBg: 'bg-slate-900',
    aiButtonHover: 'hover:bg-slate-800',
    aiButtonText: 'text-white',
    aiContentBg: 'bg-white/60',
    aiLinkText: 'text-slate-600',
    aiLinkHover: 'hover:text-slate-800',
    errorText: 'text-red-500',
    iconMuted: 'text-slate-400 hover:text-slate-600',
    emptyStateText: 'text-slate-400'
};

const createTheme = (overrides) => ({
    ...baseTheme,
    ...overrides
});

export const themes = {
    cherry: createTheme({
        bg: 'bg-pink-50',
        header: 'bg-gradient-to-r from-pink-400 to-rose-400',
        headerBorder: 'border-pink-300',
        headerText: 'text-white',
        headerButton: 'text-white hover:text-pink-100 hover:bg-pink-500',
        cardBorder: 'border-pink-200',
        subHeaderText: 'text-pink-800',
        labelText: 'text-pink-800',
        buttonBg: 'bg-pink-500',
        buttonHover: 'hover:bg-pink-600',
        infoButtonBg: 'bg-pink-50',
        infoButtonBorder: 'border-pink-200',
        infoButtonText: 'text-pink-700',
        infoButtonHover: 'hover:bg-pink-100',
        accentSoftBg: 'bg-rose-50',
        accentSoftBorder: 'border-rose-200',
        accentSoftText: 'text-rose-700',
        accentSoftHover: 'hover:bg-rose-100',
        inputBorder: 'border-pink-300',
        inputFocus: 'focus:ring-pink-500 focus:border-pink-500',
        selectFocus: 'focus:ring-pink-500 focus:border-pink-500',
        statusAttentionBg: 'bg-rose-100',
        statusAttentionText: 'text-rose-700',
        statusGoodBg: 'bg-pink-100',
        statusGoodText: 'text-pink-700',
        iconFood: 'text-pink-500',
        iconWheel: 'text-rose-500',
        iconActivity: 'text-pink-400',
        chartStrokeWheel: '#ec4899',
        chartStrokeFood: '#f472b6',
        noteBorder: 'border-pink-100',
        noteText: 'text-pink-900',
        timestampText: 'text-pink-600',
        aiCardBgFrom: 'from-pink-50',
        aiCardBgTo: 'to-rose-50',
        aiCardBorder: 'border-pink-100',
        aiHeading: 'text-pink-900',
        aiAccentText: 'text-pink-600',
        aiButtonBg: 'bg-pink-500',
        aiButtonHover: 'hover:bg-pink-600',
        aiLinkText: 'text-pink-600',
        aiLinkHover: 'hover:text-pink-800',
        iconMuted: 'text-pink-400 hover:text-pink-600',
        emptyStateText: 'text-pink-400'
    }),
    cheese: createTheme({
        bg: 'bg-yellow-50',
        header: 'bg-gradient-to-r from-amber-400 to-yellow-400',
        headerBorder: 'border-amber-300',
        headerText: 'text-white',
        headerButton: 'text-white hover:text-amber-100 hover:bg-amber-500',
        cardBorder: 'border-amber-200',
        subHeaderText: 'text-amber-800',
        labelText: 'text-amber-800',
        buttonBg: 'bg-amber-500',
        buttonHover: 'hover:bg-amber-600',
        infoButtonBg: 'bg-amber-50',
        infoButtonBorder: 'border-amber-200',
        infoButtonText: 'text-amber-700',
        infoButtonHover: 'hover:bg-amber-100',
        accentSoftBg: 'bg-orange-50',
        accentSoftBorder: 'border-orange-200',
        accentSoftText: 'text-orange-700',
        accentSoftHover: 'hover:bg-orange-100',
        inputBorder: 'border-amber-300',
        inputFocus: 'focus:ring-amber-500 focus:border-amber-500',
        selectFocus: 'focus:ring-amber-500 focus:border-amber-500',
        statusAttentionBg: 'bg-orange-100',
        statusAttentionText: 'text-orange-700',
        statusGoodBg: 'bg-amber-100',
        statusGoodText: 'text-amber-700',
        iconFood: 'text-amber-500',
        iconWheel: 'text-yellow-500',
        iconActivity: 'text-amber-400',
        chartStrokeWheel: '#f59e0b',
        chartStrokeFood: '#f97316',
        noteBorder: 'border-amber-100',
        noteText: 'text-amber-900',
        timestampText: 'text-amber-600',
        aiCardBgFrom: 'from-amber-50',
        aiCardBgTo: 'to-yellow-50',
        aiCardBorder: 'border-amber-100',
        aiHeading: 'text-amber-900',
        aiAccentText: 'text-amber-600',
        aiButtonBg: 'bg-amber-500',
        aiButtonHover: 'hover:bg-amber-600',
        aiLinkText: 'text-amber-600',
        aiLinkHover: 'hover:text-amber-800',
        iconMuted: 'text-amber-400 hover:text-amber-600',
        emptyStateText: 'text-amber-400'
    }),
    mint: createTheme({
        bg: 'bg-green-50',
        header: 'bg-gradient-to-r from-green-400 to-teal-400',
        headerBorder: 'border-green-300',
        headerText: 'text-white',
        headerButton: 'text-white hover:text-green-100 hover:bg-green-500',
        cardBorder: 'border-green-200',
        subHeaderText: 'text-green-800',
        labelText: 'text-green-800',
        buttonBg: 'bg-green-500',
        buttonHover: 'hover:bg-green-600',
        infoButtonBg: 'bg-green-50',
        infoButtonBorder: 'border-green-200',
        infoButtonText: 'text-green-800',
        infoButtonHover: 'hover:bg-green-100',
        accentSoftBg: 'bg-emerald-50',
        accentSoftBorder: 'border-emerald-200',
        accentSoftText: 'text-emerald-800',
        accentSoftHover: 'hover:bg-emerald-100',
        inputBorder: 'border-green-300',
        inputFocus: 'focus:ring-green-500 focus:border-green-500',
        selectFocus: 'focus:ring-green-500 focus:border-green-500',
        statusAttentionBg: 'bg-lime-100',
        statusAttentionText: 'text-lime-700',
        statusGoodBg: 'bg-emerald-100',
        statusGoodText: 'text-emerald-700',
        iconFood: 'text-green-500',
        iconWheel: 'text-teal-500',
        iconActivity: 'text-emerald-400',
        chartStrokeWheel: '#10b981',
        chartStrokeFood: '#14b8a6',
        noteBorder: 'border-green-100',
        noteText: 'text-green-900',
        timestampText: 'text-emerald-600',
        aiCardBgFrom: 'from-green-50',
        aiCardBgTo: 'to-teal-50',
        aiCardBorder: 'border-green-100',
        aiHeading: 'text-green-900',
        aiAccentText: 'text-green-600',
        aiButtonBg: 'bg-green-500',
        aiButtonHover: 'hover:bg-green-600',
        aiLinkText: 'text-emerald-600',
        aiLinkHover: 'hover:text-emerald-800',
        iconMuted: 'text-green-400 hover:text-green-600',
        emptyStateText: 'text-emerald-400'
    }),
    lavender: createTheme({
        bg: 'bg-purple-50',
        header: 'bg-gradient-to-r from-purple-400 to-fuchsia-400',
        headerBorder: 'border-purple-300',
        headerText: 'text-white',
        headerButton: 'text-white hover:text-purple-100 hover:bg-purple-500',
        cardBorder: 'border-purple-200',
        subHeaderText: 'text-purple-800',
        labelText: 'text-purple-800',
        buttonBg: 'bg-purple-500',
        buttonHover: 'hover:bg-purple-600',
        infoButtonBg: 'bg-purple-50',
        infoButtonBorder: 'border-purple-200',
        infoButtonText: 'text-purple-700',
        infoButtonHover: 'hover:bg-purple-100',
        accentSoftBg: 'bg-fuchsia-50',
        accentSoftBorder: 'border-fuchsia-200',
        accentSoftText: 'text-fuchsia-700',
        accentSoftHover: 'hover:bg-fuchsia-100',
        inputBorder: 'border-purple-300',
        inputFocus: 'focus:ring-purple-500 focus:border-purple-500',
        selectFocus: 'focus:ring-purple-500 focus:border-purple-500',
        statusAttentionBg: 'bg-rose-100',
        statusAttentionText: 'text-rose-700',
        statusGoodBg: 'bg-violet-100',
        statusGoodText: 'text-violet-700',
        iconFood: 'text-purple-500',
        iconWheel: 'text-fuchsia-500',
        iconActivity: 'text-purple-400',
        chartStrokeWheel: '#a855f7',
        chartStrokeFood: '#d946ef',
        noteBorder: 'border-purple-100',
        noteText: 'text-purple-900',
        timestampText: 'text-purple-600',
        aiCardBgFrom: 'from-purple-50',
        aiCardBgTo: 'to-fuchsia-50',
        aiCardBorder: 'border-purple-100',
        aiHeading: 'text-purple-900',
        aiAccentText: 'text-purple-600',
        aiButtonBg: 'bg-purple-500',
        aiButtonHover: 'hover:bg-purple-600',
        aiLinkText: 'text-purple-600',
        aiLinkHover: 'hover:text-purple-800',
        iconMuted: 'text-purple-400 hover:text-purple-600',
        emptyStateText: 'text-purple-400'
    }),
    ocean: createTheme({
        bg: 'bg-blue-50',
        header: 'bg-gradient-to-r from-blue-400 to-cyan-400',
        headerBorder: 'border-blue-300',
        headerText: 'text-white',
        headerButton: 'text-white hover:text-blue-100 hover:bg-blue-500',
        cardBorder: 'border-blue-200',
        subHeaderText: 'text-blue-800',
        labelText: 'text-blue-800',
        buttonBg: 'bg-blue-500',
        buttonHover: 'hover:bg-blue-600',
        infoButtonBg: 'bg-blue-50',
        infoButtonBorder: 'border-blue-200',
        infoButtonText: 'text-blue-700',
        infoButtonHover: 'hover:bg-blue-100',
        accentSoftBg: 'bg-cyan-50',
        accentSoftBorder: 'border-cyan-200',
        accentSoftText: 'text-cyan-700',
        accentSoftHover: 'hover:bg-cyan-100',
        inputBorder: 'border-blue-300',
        inputFocus: 'focus:ring-blue-500 focus:border-blue-500',
        selectFocus: 'focus:ring-blue-500 focus:border-blue-500',
        statusAttentionBg: 'bg-sky-100',
        statusAttentionText: 'text-sky-700',
        statusGoodBg: 'bg-blue-100',
        statusGoodText: 'text-blue-700',
        iconFood: 'text-blue-500',
        iconWheel: 'text-cyan-500',
        iconActivity: 'text-sky-500',
        chartStrokeWheel: '#3b82f6',
        chartStrokeFood: '#06b6d4',
        noteBorder: 'border-blue-100',
        noteText: 'text-blue-900',
        timestampText: 'text-blue-600',
        aiCardBgFrom: 'from-blue-50',
        aiCardBgTo: 'to-cyan-50',
        aiCardBorder: 'border-blue-100',
        aiHeading: 'text-blue-900',
        aiAccentText: 'text-blue-600',
        aiButtonBg: 'bg-blue-500',
        aiButtonHover: 'hover:bg-blue-600',
        aiLinkText: 'text-blue-600',
        aiLinkHover: 'hover:text-blue-800',
        iconMuted: 'text-blue-400 hover:text-blue-600',
        emptyStateText: 'text-blue-400'
    })
};
